### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by awvwgk** [rmera/goanalyze#1]
There are currently no installation instructions in the projects README. I could figure that I probably have to call `INSTALL.py`, but this seems to be non-standard for both go projects and Python projects. Still the install itself looks rather fragile since it modifies the PATH and PYTHONPATH variables instead of actually installing in a prefix.

Is there a way to install this project with a `setup.py` or `pip` for the Python components and the go compiler for the go components?

**Comment by rmera** [comment]
> There are currently no installation instructions in the projects README. 
It has been added, will be there in the next release. Thanks for the heads-up.

> I could figure that I probably have to call INSTALL.py
You are correct.

> Is there a way to install this project with a setup.py or pip for the Python components and the go compiler for the go components?
You can surely compile the Go part. The package is modules-aware. There is no "pip" or "setup.py" install for the package.  I think the current way is easy enough.
